// Complete Indian Stock Market Search Database
// Covers NSE Equity, BSE Equity, F&O Stocks, Indices, MCX Commodities, Currency

export const stockDatabase = [
  // ═══════════════════════════════════════
  // INDICES
  // ═══════════════════════════════════════
  { name: "Nifty 50", symbol: "NIFTY", type: "Index", exchange: "NSE" },
  { name: "Nifty Bank", symbol: "BANKNIFTY", type: "Index", exchange: "NSE" },
  { name: "Nifty IT", symbol: "NIFTYIT", type: "Index", exchange: "NSE" },
  { name: "Nifty Pharma", symbol: "NIFTYPHARMA", type: "Index", exchange: "NSE" },
  { name: "Nifty Auto", symbol: "NIFTYAUTO", type: "Index", exchange: "NSE" },
  { name: "Nifty FMCG", symbol: "NIFTYFMCG", type: "Index", exchange: "NSE" },
  { name: "Nifty Metal", symbol: "NIFTYMETAL", type: "Index", exchange: "NSE" },
  { name: "Nifty Energy", symbol: "NIFTYENERGY", type: "Index", exchange: "NSE" },
  { name: "Nifty Realty", symbol: "NIFTYREALTY", type: "Index", exchange: "NSE" },
  { name: "Nifty Midcap 50", symbol: "NIFTYMIDCAP50", type: "Index", exchange: "NSE" },
  { name: "Nifty Midcap 100", symbol: "NIFTYMIDCAP100", type: "Index", exchange: "NSE" },
  { name: "Nifty Smallcap 100", symbol: "NIFTYSMALLCAP100", type: "Index", exchange: "NSE" },
  { name: "Nifty Next 50", symbol: "NIFTYNEXT50", type: "Index", exchange: "NSE" },
  { name: "Nifty 100", symbol: "NIFTY100", type: "Index", exchange: "NSE" },
  { name: "Nifty 200", symbol: "NIFTY200", type: "Index", exchange: "NSE" },
  { name: "Nifty 500", symbol: "NIFTY500", type: "Index", exchange: "NSE" },
  { name: "Sensex", symbol: "SENSEX", type: "Index", exchange: "BSE" },
  { name: "BSE 100", symbol: "BSE100", type: "Index", exchange: "BSE" },
  { name: "BSE 200", symbol: "BSE200", type: "Index", exchange: "BSE" },
  { name: "BSE Midcap", symbol: "BSEMIDCAP", type: "Index", exchange: "BSE" },
  { name: "BSE Smallcap", symbol: "BSESMALLCAP", type: "Index", exchange: "BSE" },
  { name: "Fin Nifty", symbol: "FINNIFTY", type: "Index", exchange: "NSE" },
  { name: "Nifty PSE", symbol: "NIFTYPSE", type: "Index", exchange: "NSE" },
  { name: "Nifty Infra", symbol: "NIFTYINFRA", type: "Index", exchange: "NSE" },

  // ═══════════════════════════════════════
  // MCX COMMODITIES
  // ═══════════════════════════════════════
  { name: "Gold", symbol: "GOLD", type: "Commodity", exchange: "MCX" },
  { name: "Gold Mini", symbol: "GOLDM", type: "Commodity", exchange: "MCX" },
  { name: "Gold Petal", symbol: "GOLDPETAL", type: "Commodity", exchange: "MCX" },
  { name: "Silver", symbol: "SILVER", type: "Commodity", exchange: "MCX" },
  { name: "Silver Mini", symbol: "SILVERM", type: "Commodity", exchange: "MCX" },
  { name: "Silver Micro", symbol: "SILVERMIC", type: "Commodity", exchange: "MCX" },
  { name: "Crude Oil", symbol: "CRUDEOIL", type: "Commodity", exchange: "MCX" },
  { name: "Crude Oil Mini", symbol: "CRUDEOILM", type: "Commodity", exchange: "MCX" },
  { name: "Natural Gas", symbol: "NATURALGAS", type: "Commodity", exchange: "MCX" },
  { name: "Natural Gas Mini", symbol: "NATURALGASM", type: "Commodity", exchange: "MCX" },
  { name: "Copper", symbol: "COPPER", type: "Commodity", exchange: "MCX" },
  { name: "Copper Mini", symbol: "COPPERM", type: "Commodity", exchange: "MCX" },
  { name: "Zinc", symbol: "ZINC", type: "Commodity", exchange: "MCX" },
  { name: "Zinc Mini", symbol: "ZINCM", type: "Commodity", exchange: "MCX" },
  { name: "Aluminium", symbol: "ALUMINIUM", type: "Commodity", exchange: "MCX" },
  { name: "Aluminium Mini", symbol: "ALUMINIUMM", type: "Commodity", exchange: "MCX" },
  { name: "Lead", symbol: "LEAD", type: "Commodity", exchange: "MCX" },
  { name: "Lead Mini", symbol: "LEADM", type: "Commodity", exchange: "MCX" },
  { name: "Nickel", symbol: "NICKEL", type: "Commodity", exchange: "MCX" },
  { name: "Tin", symbol: "TIN", type: "Commodity", exchange: "MCX" },
  { name: "Mentha Oil", symbol: "MENTHAOIL", type: "Commodity", exchange: "MCX" },
  { name: "Cotton", symbol: "COTTON", type: "Commodity", exchange: "MCX" },
  { name: "Castor Seed", symbol: "CASTORSEED", type: "Commodity", exchange: "NCDEX" },
  { name: "Soybean", symbol: "SOYBEAN", type: "Commodity", exchange: "NCDEX" },
  { name: "Crude Palm Oil", symbol: "CPO", type: "Commodity", exchange: "MCX" },

  // ═══════════════════════════════════════
  // CURRENCY PAIRS
  // ═══════════════════════════════════════
  { name: "USD/INR", symbol: "USDINR", type: "Currency", exchange: "NSE" },
  { name: "EUR/INR", symbol: "EURINR", type: "Currency", exchange: "NSE" },
  { name: "GBP/INR", symbol: "GBPINR", type: "Currency", exchange: "NSE" },
  { name: "JPY/INR", symbol: "JPYINR", type: "Currency", exchange: "NSE" },

  // ═══════════════════════════════════════
  // NIFTY 50 STOCKS (F&O Eligible)
  // ═══════════════════════════════════════
  { name: "Reliance Industries", symbol: "RELIANCE", type: "Stock", exchange: "NSE", fo: true },
  { name: "Tata Consultancy Services", symbol: "TCS", type: "Stock", exchange: "NSE", fo: true },
  { name: "HDFC Bank", symbol: "HDFCBANK", type: "Stock", exchange: "NSE", fo: true },
  { name: "Infosys", symbol: "INFY", type: "Stock", exchange: "NSE", fo: true },
  { name: "ICICI Bank", symbol: "ICICIBANK", type: "Stock", exchange: "NSE", fo: true },
  { name: "Hindustan Unilever", symbol: "HINDUNILVR", type: "Stock", exchange: "NSE", fo: true },
  { name: "ITC", symbol: "ITC", type: "Stock", exchange: "NSE", fo: true },
  { name: "State Bank of India", symbol: "SBIN", type: "Stock", exchange: "NSE", fo: true },
  { name: "Bharti Airtel", symbol: "BHARTIARTL", type: "Stock", exchange: "NSE", fo: true },
  { name: "Kotak Mahindra Bank", symbol: "KOTAKBANK", type: "Stock", exchange: "NSE", fo: true },
  { name: "Larsen & Toubro", symbol: "LT", type: "Stock", exchange: "NSE", fo: true },
  { name: "Axis Bank", symbol: "AXISBANK", type: "Stock", exchange: "NSE", fo: true },
  { name: "Asian Paints", symbol: "ASIANPAINT", type: "Stock", exchange: "NSE", fo: true },
  { name: "Maruti Suzuki", symbol: "MARUTI", type: "Stock", exchange: "NSE", fo: true },
  { name: "Sun Pharmaceutical", symbol: "SUNPHARMA", type: "Stock", exchange: "NSE", fo: true },
  { name: "Wipro", symbol: "WIPRO", type: "Stock", exchange: "NSE", fo: true },
  { name: "HCL Technologies", symbol: "HCLTECH", type: "Stock", exchange: "NSE", fo: true },
  { name: "Bajaj Finance", symbol: "BAJFINANCE", type: "Stock", exchange: "NSE", fo: true },
  { name: "Titan Company", symbol: "TITAN", type: "Stock", exchange: "NSE", fo: true },
  { name: "Nestle India", symbol: "NESTLEIND", type: "Stock", exchange: "NSE", fo: true },
  { name: "Tech Mahindra", symbol: "TECHM", type: "Stock", exchange: "NSE", fo: true },
  { name: "UltraTech Cement", symbol: "ULTRACEMCO", type: "Stock", exchange: "NSE", fo: true },
  { name: "NTPC", symbol: "NTPC", type: "Stock", exchange: "NSE", fo: true },
  { name: "Power Grid Corporation", symbol: "POWERGRID", type: "Stock", exchange: "NSE", fo: true },
  { name: "Mahindra & Mahindra", symbol: "M&M", type: "Stock", exchange: "NSE", fo: true },
  { name: "ONGC", symbol: "ONGC", type: "Stock", exchange: "NSE", fo: true },
  { name: "Coal India", symbol: "COALINDIA", type: "Stock", exchange: "NSE", fo: true },
  { name: "Tata Motors", symbol: "TATAMOTORS", type: "Stock", exchange: "NSE", fo: true },
  { name: "Tata Steel", symbol: "TATASTEEL", type: "Stock", exchange: "NSE", fo: true },
  { name: "JSW Steel", symbol: "JSWSTEEL", type: "Stock", exchange: "NSE", fo: true },
  { name: "Hindalco Industries", symbol: "HINDALCO", type: "Stock", exchange: "NSE", fo: true },
  { name: "Grasim Industries", symbol: "GRASIM", type: "Stock", exchange: "NSE", fo: true },
  { name: "Dr Reddy's Laboratories", symbol: "DRREDDY", type: "Stock", exchange: "NSE", fo: true },
  { name: "Cipla", symbol: "CIPLA", type: "Stock", exchange: "NSE", fo: true },
  { name: "Eicher Motors", symbol: "EICHERMOT", type: "Stock", exchange: "NSE", fo: true },
  { name: "Hero MotoCorp", symbol: "HEROMOTOCO", type: "Stock", exchange: "NSE", fo: true },
  { name: "Bajaj Auto", symbol: "BAJAJ-AUTO", type: "Stock", exchange: "NSE", fo: true },
  { name: "Bajaj Finserv", symbol: "BAJAJFINSV", type: "Stock", exchange: "NSE", fo: true },
  { name: "Divi's Laboratories", symbol: "DIVISLAB", type: "Stock", exchange: "NSE", fo: true },
  { name: "Britannia Industries", symbol: "BRITANNIA", type: "Stock", exchange: "NSE", fo: true },
  { name: "Apollo Hospitals", symbol: "APOLLOHOSP", type: "Stock", exchange: "NSE", fo: true },
  { name: "Adani Enterprises", symbol: "ADANIENT", type: "Stock", exchange: "NSE", fo: true },
  { name: "Adani Ports", symbol: "ADANIPORTS", type: "Stock", exchange: "NSE", fo: true },
  { name: "Tata Consumer Products", symbol: "TATACONSUM", type: "Stock", exchange: "NSE", fo: true },
  { name: "IndusInd Bank", symbol: "INDUSINDBK", type: "Stock", exchange: "NSE", fo: true },
  { name: "Shriram Finance", symbol: "SHRIRAMFIN", type: "Stock", exchange: "NSE", fo: true },
  { name: "BEL", symbol: "BEL", type: "Stock", exchange: "NSE", fo: true },
  { name: "Trent", symbol: "TRENT", type: "Stock", exchange: "NSE", fo: true },
  { name: "Zomato", symbol: "ZOMATO", type: "Stock", exchange: "NSE", fo: true },

  // ═══════════════════════════════════════
  // POPULAR F&O STOCKS (Beyond Nifty 50)
  // ═══════════════════════════════════════
  { name: "Adani Green Energy", symbol: "ADANIGREEN", type: "Stock", exchange: "NSE", fo: true },
  { name: "Adani Power", symbol: "ADANIPOWER", type: "Stock", exchange: "NSE", fo: true },
  { name: "Adani Total Gas", symbol: "ATGL", type: "Stock", exchange: "NSE", fo: true },
  { name: "Adani Wilmar", symbol: "AWL", type: "Stock", exchange: "NSE", fo: true },
  { name: "Ambuja Cements", symbol: "AMBUJACEM", type: "Stock", exchange: "NSE", fo: true },
  { name: "ACC", symbol: "ACC", type: "Stock", exchange: "NSE", fo: true },
  { name: "Ashok Leyland", symbol: "ASHOKLEY", type: "Stock", exchange: "NSE", fo: true },
  { name: "Avenue Supermarts (DMart)", symbol: "DMART", type: "Stock", exchange: "NSE", fo: true },
  { name: "Bank of Baroda", symbol: "BANKBARODA", type: "Stock", exchange: "NSE", fo: true },
  { name: "BPCL", symbol: "BPCL", type: "Stock", exchange: "NSE", fo: true },
  { name: "Canara Bank", symbol: "CANBK", type: "Stock", exchange: "NSE", fo: true },
  { name: "CDSL", symbol: "CDSL", type: "Stock", exchange: "NSE", fo: true },
  { name: "Cholamandalam Investment", symbol: "CHOLAFIN", type: "Stock", exchange: "NSE", fo: true },
  { name: "Cummins India", symbol: "CUMMINSIND", type: "Stock", exchange: "NSE", fo: true },
  { name: "DLF", symbol: "DLF", type: "Stock", exchange: "NSE", fo: true },
  { name: "Federal Bank", symbol: "FEDERALBNK", type: "Stock", exchange: "NSE", fo: true },
  { name: "GAIL India", symbol: "GAIL", type: "Stock", exchange: "NSE", fo: true },
  { name: "GMR Airports", symbol: "GMRINFRA", type: "Stock", exchange: "NSE", fo: true },
  { name: "Godrej Consumer Products", symbol: "GODREJCP", type: "Stock", exchange: "NSE", fo: true },
  { name: "Godrej Properties", symbol: "GODREJPROP", type: "Stock", exchange: "NSE", fo: true },
  { name: "HAL", symbol: "HAL", type: "Stock", exchange: "NSE", fo: true },
  { name: "Havells India", symbol: "HAVELLS", type: "Stock", exchange: "NSE", fo: true },
  { name: "HDFC Asset Management", symbol: "HDFCAMC", type: "Stock", exchange: "NSE", fo: true },
  { name: "HDFC Life Insurance", symbol: "HDFCLIFE", type: "Stock", exchange: "NSE", fo: true },
  { name: "Hindustan Aeronautics", symbol: "HAL", type: "Stock", exchange: "NSE", fo: true },
  { name: "Hindustan Zinc", symbol: "HINDZINC", type: "Stock", exchange: "NSE", fo: true },
  { name: "ICICI Lombard", symbol: "ICICIGI", type: "Stock", exchange: "NSE", fo: true },
  { name: "ICICI Prudential Life", symbol: "ICICIPRULI", type: "Stock", exchange: "NSE", fo: true },
  { name: "Indian Hotel Company (Taj)", symbol: "INDHOTEL", type: "Stock", exchange: "NSE", fo: true },
  { name: "Indian Oil Corporation", symbol: "IOC", type: "Stock", exchange: "NSE", fo: true },
  { name: "Indian Railway Finance Corp", symbol: "IRFC", type: "Stock", exchange: "NSE", fo: true },
  { name: "IRCTC", symbol: "IRCTC", type: "Stock", exchange: "NSE", fo: true },
  { name: "Interglobe Aviation (IndiGo)", symbol: "INDIGO", type: "Stock", exchange: "NSE", fo: true },
  { name: "Jubilant FoodWorks", symbol: "JUBLFOOD", type: "Stock", exchange: "NSE", fo: true },
  { name: "L&T Finance", symbol: "LTF", type: "Stock", exchange: "NSE", fo: true },
  { name: "LTIMindtree", symbol: "LTIM", type: "Stock", exchange: "NSE", fo: true },
  { name: "Lodha (Macrotech Dev)", symbol: "LODHA", type: "Stock", exchange: "NSE", fo: true },
  { name: "Lupin", symbol: "LUPIN", type: "Stock", exchange: "NSE", fo: true },
  { name: "Max Healthcare", symbol: "MAXHEALTH", type: "Stock", exchange: "NSE", fo: true },
  { name: "Muthoot Finance", symbol: "MUTHOOTFIN", type: "Stock", exchange: "NSE", fo: true },
  { name: "Naukri (Info Edge)", symbol: "NAUKRI", type: "Stock", exchange: "NSE", fo: true },
  { name: "NMDC", symbol: "NMDC", type: "Stock", exchange: "NSE", fo: true },
  { name: "Nykaa (FSN E-Commerce)", symbol: "NYKAA", type: "Stock", exchange: "NSE", fo: true },
  { name: "Oberoi Realty", symbol: "OBEROIRLTY", type: "Stock", exchange: "NSE", fo: true },
  { name: "Oil India", symbol: "OIL", type: "Stock", exchange: "NSE", fo: true },
  { name: "Page Industries", symbol: "PAGEIND", type: "Stock", exchange: "NSE", fo: true },
  { name: "Paytm (One97 Communications)", symbol: "PAYTM", type: "Stock", exchange: "NSE", fo: true },
  { name: "PB Fintech (Policybazaar)", symbol: "POLICYBZR", type: "Stock", exchange: "NSE", fo: true },
  { name: "Persistent Systems", symbol: "PERSISTENT", type: "Stock", exchange: "NSE", fo: true },
  { name: "Pidilite Industries", symbol: "PIDILITIND", type: "Stock", exchange: "NSE", fo: true },
  { name: "PNB Housing Finance", symbol: "PNBHOUSING", type: "Stock", exchange: "NSE", fo: true },
  { name: "Punjab National Bank", symbol: "PNB", type: "Stock", exchange: "NSE", fo: true },
  { name: "Rail Vikas Nigam", symbol: "RVNL", type: "Stock", exchange: "NSE", fo: true },
  { name: "SBI Cards", symbol: "SBICARD", type: "Stock", exchange: "NSE", fo: true },
  { name: "SBI Life Insurance", symbol: "SBILIFE", type: "Stock", exchange: "NSE", fo: true },
  { name: "Shree Cement", symbol: "SHREECEM", type: "Stock", exchange: "NSE", fo: true },
  { name: "Siemens India", symbol: "SIEMENS", type: "Stock", exchange: "NSE", fo: true },
  { name: "Solar Industries", symbol: "SOLARINDS", type: "Stock", exchange: "NSE", fo: true },
  { name: "Suzlon Energy", symbol: "SUZLON", type: "Stock", exchange: "NSE", fo: true },
  { name: "Torrent Pharmaceuticals", symbol: "TORNTPHARM", type: "Stock", exchange: "NSE", fo: true },
  { name: "TVS Motor Company", symbol: "TVSMOTOR", type: "Stock", exchange: "NSE", fo: true },
  { name: "UPL", symbol: "UPL", type: "Stock", exchange: "NSE", fo: true },
  { name: "Varun Beverages", symbol: "VBL", type: "Stock", exchange: "NSE", fo: true },
  { name: "Vedanta", symbol: "VEDL", type: "Stock", exchange: "NSE", fo: true },
  { name: "Vodafone Idea", symbol: "IDEA", type: "Stock", exchange: "NSE", fo: true },
  { name: "Voltas", symbol: "VOLTAS", type: "Stock", exchange: "NSE", fo: true },
  { name: "Zydus Lifesciences", symbol: "ZYDUSLIFE", type: "Stock", exchange: "NSE", fo: true },
  { name: "ABB India", symbol: "ABB", type: "Stock", exchange: "NSE", fo: true },
  { name: "Aditya Birla Capital", symbol: "ABCAPITAL", type: "Stock", exchange: "NSE", fo: true },
  { name: "Aditya Birla Fashion", symbol: "ABFRL", type: "Stock", exchange: "NSE", fo: true },
  { name: "Balkrishna Industries", symbol: "BALKRISIND", type: "Stock", exchange: "NSE", fo: true },
  { name: "Berger Paints", symbol: "BERGEPAINT", type: "Stock", exchange: "NSE", fo: true },
  { name: "Biocon", symbol: "BIOCON", type: "Stock", exchange: "NSE", fo: true },
  { name: "Coforge", symbol: "COFORGE", type: "Stock", exchange: "NSE", fo: true },
  { name: "Colgate-Palmolive India", symbol: "COLPAL", type: "Stock", exchange: "NSE", fo: true },
  { name: "Container Corporation", symbol: "CONCOR", type: "Stock", exchange: "NSE", fo: true },
  { name: "Crompton Greaves Consumer", symbol: "CROMPTON", type: "Stock", exchange: "NSE", fo: true },
  { name: "Deepak Nitrite", symbol: "DEEPAKNTR", type: "Stock", exchange: "NSE", fo: true },
  { name: "Dixon Technologies", symbol: "DIXON", type: "Stock", exchange: "NSE", fo: true },
  { name: "Exide Industries", symbol: "EXIDEIND", type: "Stock", exchange: "NSE", fo: true },
  { name: "Fortis Healthcare", symbol: "FORTIS", type: "Stock", exchange: "NSE", fo: true },
  { name: "HDFC Bank", symbol: "HDFCBANK", type: "Stock", exchange: "NSE", fo: true },
  { name: "IDFC First Bank", symbol: "IDFCFIRSTB", type: "Stock", exchange: "NSE", fo: true },
  { name: "IREDA", symbol: "IREDA", type: "Stock", exchange: "NSE", fo: true },
  { name: "Kansai Nerolac Paints", symbol: "KANSAINER", type: "Stock", exchange: "NSE", fo: true },
  { name: "Kaynes Technology", symbol: "KAYNES", type: "Stock", exchange: "NSE", fo: true },
  { name: "Laurus Labs", symbol: "LAURUSLABS", type: "Stock", exchange: "NSE", fo: true },
  { name: "MRF", symbol: "MRF", type: "Stock", exchange: "NSE", fo: true },
  { name: "Marico", symbol: "MARICO", type: "Stock", exchange: "NSE", fo: true },
  { name: "MphasiS", symbol: "MPHASIS", type: "Stock", exchange: "NSE", fo: true },
  { name: "NHPC", symbol: "NHPC", type: "Stock", exchange: "NSE", fo: true },
  { name: "Polycab India", symbol: "POLYCAB", type: "Stock", exchange: "NSE", fo: true },
  { name: "Power Finance Corporation", symbol: "PFC", type: "Stock", exchange: "NSE", fo: true },
  { name: "REC Limited", symbol: "RECLTD", type: "Stock", exchange: "NSE", fo: true },
  { name: "Samvardhana Motherson", symbol: "MOTHERSON", type: "Stock", exchange: "NSE", fo: true },
  { name: "Tata Communications", symbol: "TATACOMM", type: "Stock", exchange: "NSE", fo: true },
  { name: "Tata Elxsi", symbol: "TATAELXSI", type: "Stock", exchange: "NSE", fo: true },
  { name: "Tata Power", symbol: "TATAPOWER", type: "Stock", exchange: "NSE", fo: true },
  { name: "Union Bank of India", symbol: "UNIONBANK", type: "Stock", exchange: "NSE", fo: true },
  { name: "United Spirits", symbol: "MCDOWELL-N", type: "Stock", exchange: "NSE", fo: true },
  { name: "Wipro", symbol: "WIPRO", type: "Stock", exchange: "NSE", fo: true },
  { name: "YES Bank", symbol: "YESBANK", type: "Stock", exchange: "NSE", fo: true },
  { name: "Alkem Laboratories", symbol: "ALKEM", type: "Stock", exchange: "NSE", fo: true },
  { name: "Apollo Tyres", symbol: "APOLLOTYRE", type: "Stock", exchange: "NSE", fo: true },
  { name: "Astral", symbol: "ASTRAL", type: "Stock", exchange: "NSE", fo: true },
  { name: "Atul", symbol: "ATUL", type: "Stock", exchange: "NSE", fo: true },
  { name: "AU Small Finance Bank", symbol: "AUBANK", type: "Stock", exchange: "NSE", fo: true },
  { name: "Bandhan Bank", symbol: "BANDHANBNK", type: "Stock", exchange: "NSE", fo: true },
  { name: "Bharat Electronics", symbol: "BEL", type: "Stock", exchange: "NSE", fo: true },
  { name: "Bharat Forge", symbol: "BHARATFORG", type: "Stock", exchange: "NSE", fo: true },
  { name: "Bharat Heavy Electricals", symbol: "BHEL", type: "Stock", exchange: "NSE", fo: true },
  { name: "Bharat Petroleum", symbol: "BPCL", type: "Stock", exchange: "NSE", fo: true },
  { name: "BSE Limited", symbol: "BSE", type: "Stock", exchange: "NSE", fo: true },
  { name: "Carborundum Universal", symbol: "CARBORUNIV", type: "Stock", exchange: "NSE", fo: true },
  { name: "Ceat", symbol: "CEATLTD", type: "Stock", exchange: "NSE", fo: true },
  { name: "Century Textiles", symbol: "CENTURYTEX", type: "Stock", exchange: "NSE", fo: true },
  { name: "CG Power", symbol: "CGPOWER", type: "Stock", exchange: "NSE", fo: true },
  { name: "City Union Bank", symbol: "CUB", type: "Stock", exchange: "NSE", fo: true },
  { name: "Dabur India", symbol: "DABUR", type: "Stock", exchange: "NSE", fo: true },
  { name: "Emami", symbol: "EMAMILTD", type: "Stock", exchange: "NSE", fo: true },
  { name: "Escorts Kubota", symbol: "ESCORTS", type: "Stock", exchange: "NSE", fo: true },
  { name: "Galaxy Surfactants", symbol: "GALAXYSURF", type: "Stock", exchange: "NSE", fo: true },
  { name: "Godrej Agrovet", symbol: "GODREJAGRO", type: "Stock", exchange: "NSE", fo: true },
  { name: "Granules India", symbol: "GRANULES", type: "Stock", exchange: "NSE", fo: true },
  { name: "Gujarat Gas", symbol: "GUJGASLTD", type: "Stock", exchange: "NSE", fo: true },
  { name: "Gujarat State Petronet", symbol: "GSPL", type: "Stock", exchange: "NSE", fo: true },
  { name: "Hindustan Copper", symbol: "HINDCOPPER", type: "Stock", exchange: "NSE", fo: true },
  { name: "HUDCO", symbol: "HUDCO", type: "Stock", exchange: "NSE", fo: true },
  { name: "ICICI Securities", symbol: "ISEC", type: "Stock", exchange: "NSE", fo: true },
  { name: "India Cements", symbol: "INDIACEM", type: "Stock", exchange: "NSE", fo: true },
  { name: "Indian Energy Exchange", symbol: "IEX", type: "Stock", exchange: "NSE", fo: true },
  { name: "IDBI Bank", symbol: "IDBI", type: "Stock", exchange: "NSE", fo: true },
  { name: "INOX Wind", symbol: "INOXWIND", type: "Stock", exchange: "NSE", fo: true },
  { name: "IPCA Laboratories", symbol: "IPCALAB", type: "Stock", exchange: "NSE", fo: true },
  { name: "J.B. Chemicals", symbol: "JBCHEPHARM", type: "Stock", exchange: "NSE", fo: true },
  { name: "JSW Energy", symbol: "JSWENERGY", type: "Stock", exchange: "NSE", fo: true },
  { name: "JK Cement", symbol: "JKCEMENT", type: "Stock", exchange: "NSE", fo: true },
  { name: "Kalyan Jewellers", symbol: "KALYANKJIL", type: "Stock", exchange: "NSE", fo: true },
  { name: "KEI Industries", symbol: "KEI", type: "Stock", exchange: "NSE", fo: true },
  { name: "Kpit Technologies", symbol: "KPITTECH", type: "Stock", exchange: "NSE", fo: true },
  { name: "Manappuram Finance", symbol: "MANAPPURAM", type: "Stock", exchange: "NSE", fo: true },
  { name: "Max Financial Services", symbol: "MFSL", type: "Stock", exchange: "NSE", fo: true },
  { name: "MCX India", symbol: "MCX", type: "Stock", exchange: "NSE", fo: true },
  { name: "Metropolis Healthcare", symbol: "METROPOLIS", type: "Stock", exchange: "NSE", fo: true },
  { name: "Minda Industries", symbol: "MINDAIND", type: "Stock", exchange: "NSE", fo: true },
  { name: "Natco Pharma", symbol: "NATCOPHARM", type: "Stock", exchange: "NSE", fo: true },
  { name: "Network18 Media", symbol: "NETWORK18", type: "Stock", exchange: "NSE", fo: true },
  { name: "Nippon India AMC", symbol: "NAM-INDIA", type: "Stock", exchange: "NSE", fo: true },
  { name: "NOCIL", symbol: "NOCIL", type: "Stock", exchange: "NSE", fo: true },
  { name: "Patanjali Foods", symbol: "PATANJALI", type: "Stock", exchange: "NSE", fo: true },
  { name: "Phoenix Mills", symbol: "PHOENIXLTD", type: "Stock", exchange: "NSE", fo: true },
  { name: "PI Industries", symbol: "PIIND", type: "Stock", exchange: "NSE", fo: true },
  { name: "Piramal Enterprises", symbol: "PEL", type: "Stock", exchange: "NSE", fo: true },
  { name: "Prestige Estates", symbol: "PRESTIGE", type: "Stock", exchange: "NSE", fo: true },
  { name: "Procter & Gamble Hygiene", symbol: "PGHH", type: "Stock", exchange: "NSE", fo: true },
  { name: "PVR Inox", symbol: "PVRINOX", type: "Stock", exchange: "NSE", fo: true },
  { name: "Relaxo Footwear", symbol: "RELAXO", type: "Stock", exchange: "NSE", fo: true },
  { name: "Route Mobile", symbol: "ROUTE", type: "Stock", exchange: "NSE", fo: true },
  { name: "SAIL", symbol: "SAIL", type: "Stock", exchange: "NSE", fo: true },
  { name: "SRF", symbol: "SRF", type: "Stock", exchange: "NSE", fo: true },
  { name: "Star Health Insurance", symbol: "STARHEALTH", type: "Stock", exchange: "NSE", fo: true },
  { name: "Sterlite Technologies", symbol: "STLTECH", type: "Stock", exchange: "NSE", fo: true },
  { name: "Sumitomo Chemical India", symbol: "SUMICHEM", type: "Stock", exchange: "NSE", fo: true },
  { name: "Sundaram Finance", symbol: "SUNDARMFIN", type: "Stock", exchange: "NSE", fo: true },
  { name: "Tata Chemicals", symbol: "TATACHEM", type: "Stock", exchange: "NSE", fo: true },
  { name: "Thermax", symbol: "THERMAX", type: "Stock", exchange: "NSE", fo: true },
  { name: "Thyrocare", symbol: "THYROCARE", type: "Stock", exchange: "NSE", fo: true },
  { name: "Time Technoplast", symbol: "TIMETECHNO", type: "Stock", exchange: "NSE", fo: true },
  { name: "Torrent Power", symbol: "TORNTPOWER", type: "Stock", exchange: "NSE", fo: true },
  { name: "Trident", symbol: "TRIDENT", type: "Stock", exchange: "NSE", fo: true },
  { name: "Tube Investments", symbol: "TIINDIA", type: "Stock", exchange: "NSE", fo: true },
  { name: "UTI AMC", symbol: "UTIAMC", type: "Stock", exchange: "NSE", fo: true },
  { name: "Vinati Organics", symbol: "VINATIORGA", type: "Stock", exchange: "NSE", fo: true },
  { name: "Whirlpool India", symbol: "WHIRLPOOL", type: "Stock", exchange: "NSE", fo: true },
  { name: "Wipro", symbol: "WIPRO", type: "Stock", exchange: "NSE", fo: true },
  { name: "Zensar Technologies", symbol: "ZENSARTECH", type: "Stock", exchange: "NSE", fo: true },
  { name: "Zee Entertainment", symbol: "ZEEL", type: "Stock", exchange: "NSE", fo: true },
];

// Search function
export function searchStocks(query) {
  if (!query || query.trim().length < 1) return [];
  const q = query.trim().toLowerCase();
  return stockDatabase
    .filter((s) =>
      s.name.toLowerCase().includes(q) ||
      s.symbol.toLowerCase().includes(q)
    )
    .sort((a, b) => {
      // Exact symbol match first
      if (a.symbol.toLowerCase() === q) return -1;
      if (b.symbol.toLowerCase() === q) return 1;
      // Symbol starts with query
      if (a.symbol.toLowerCase().startsWith(q)) return -1;
      if (b.symbol.toLowerCase().startsWith(q)) return 1;
      // Name starts with query
      if (a.name.toLowerCase().startsWith(q)) return -1;
      if (b.name.toLowerCase().startsWith(q)) return 1;
      return 0;
    })
    .slice(0, 10);
}
